name: Manual release intelchain (need tag)

on: 
  workflow_dispatch:
    inputs:
      tag: 
        decription: 'tag value to create the release'
        required: true

jobs:
  check:
    name: Per-check for current tag
    runs-on: ubuntu-22.04
    continue-on-error: false
    outputs:
      tag_annotated: ${{ steps.check-tag-annotated.outputs.tag_annotated }}

    steps:
      - name: Checkout intelchain core code
        uses: actions/checkout@v3
        with:
          path: intelchain
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Check tag annotated
        id: check-tag-annotated
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1)
          if git rev-parse $VERSION^{tag} -- &>/dev/null
          then
            echo "::set-output name=tag_annotated::true"
          else
            echo "::set-output name=tag_annotated::false"
          fi
        working-directory: intelchain

  build:
    name: Build intelchain binary
    needs: check
    runs-on: ${{ matrix.os }}
    if: needs.check.outputs.tag_annotated == 'true'
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, [self-hosted, linux, ARM64]]

    steps:
      - name: Import GPG key
        if: join(matrix.os, '-') != 'self-hosted-linux-ARM64'
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASS }}

      - name: Checkout dependence repo
        uses: actions/checkout@v3
        with:
          repository: intelchain-itc/mcl
          path: mcl

      - name: Checkout dependence repo
        uses: actions/checkout@v3
        with:
          repository: intelchain-itc/bls
          path: bls

      - name: Checkout intelchain core code
        uses: actions/checkout@v3
        with:
          path: intelchain
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Set up Go go.mod
        uses: actions/setup-go@v3
        with:
          go-version-file: 'intelchain/go.mod'

      - name: Get latest version and release
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1 | tr -d v)
          RELEASE=$(git describe --long | cut -f2 -d-)
          echo "build_version=$VERSION" >> $GITHUB_ENV
          echo "build_release=$RELEASE" >> $GITHUB_ENV
        working-directory: intelchain

      - name: Build intelchain binary and packages for Linux
        if: matrix.os == 'ubuntu-22.04'
        run: |
          make linux_static
          make deb
          echo %_signature gpg >> $HOME/.rpmmacros && echo "%_gpg_name Intelchain (intelchain.org)" >> $HOME/.rpmmacros
          make rpm
          mv ./bin/intelchain ./bin/intelchain-amd64
          mv $HOME/debbuild/intelchain-$build_version-$build_release.deb ./bin/
          mv $HOME/rpmbuild/RPMS/x86_64/intelchain-$build_version-$build_release.x86_64.rpm ./bin/
        working-directory: intelchain

      - name: Build intelchain binary and packages for Linux on ARM64
        if: join(matrix.os, '-') == 'self-hosted-linux-ARM64'
        run: |
          make linux_static
          mv ./bin/intelchain ./bin/intelchain-arm64
        working-directory: intelchain

      - name: Build intelchain binary and packages for MacOS
        if: matrix.os == 'macos-12'
        run: |
          brew install bash
          sudo rm -f /usr/local/opt/openssl
          sudo ln -sf /usr/local/opt/openssl@1.1 /usr/local/opt/openssl
          make
          cd ./bin && mkdir ./lib && mv ./*.dylib ./lib && rm -f ./bootnode
          gpg --detach-sign intelchain
          zip -qr ./intelchain-macos.zip ./*
          rm -rf `ls * | egrep -v intelchain-macos.zip`
        working-directory: intelchain

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: intelchain
          path: intelchain/bin/*
          retention-days: 1

  docker-build:
    name: Build and push intelchain docker image
    needs: [check, build]
    runs-on: ubuntu-22.04
    if: needs.check.outputs.tag_annotated == 'true'

    steps:
      - name: Checkout intelchain core code
        uses: actions/checkout@v3
        with:
          path: intelchain
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Get latest version
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1 | tr -d v)
          RELEASE=$(git describe --long | cut -f2 -d-)
          echo "build_version=$VERSION" >> $GITHUB_ENV
          echo "build_release=$RELEASE" >> $GITHUB_ENV
        working-directory: intelchain

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: intelchain

      - name: Build preview works
        run: |
          mv $GITHUB_WORKSPACE/intelchain-amd64 ./scripts/docker/intelchain
        working-directory: intelchain
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./intelchain/scripts/docker
          file: ./intelchain/scripts/docker/Dockerfile
          push: true
          tags: |
            intelchainitc/intelchain:${{ github.event.inputs.tag }}
            intelchainitc/intelchain:${{ env.build_version }}-${{ env.build_release }}

  release-page:
    name: Sign binary and create and publish release page
    needs: [check, build]
    runs-on: ubuntu-22.04
    if: needs.check.outputs.tag_annotated == 'true'

    steps:
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASS }}

      - name: Checkout intelchain core code
        uses: actions/checkout@v3
        with:
          path: intelchain
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Get latest version
        run: |
          VERSION=$(git tag -l --sort=-v:refname | head -n 1 | tr -d v)
          VERSION_LONG=$(git describe --always --long --dirty)
          RELEASE=$(git describe --long | cut -f2 -d-)
          echo "build_version=$VERSION" >> $GITHUB_ENV
          echo "build_version_long=$VERSION_LONG" >> $GITHUB_ENV
          echo "build_release=$RELEASE" >> $GITHUB_ENV
        working-directory: intelchain

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: intelchain

      - name: Signed amd64 intelchain binary
        run: |
          gpg --detach-sign intelchain-amd64
          sha256sum intelchain-amd64 >> intelchain-amd64.sha256

      - name: Signed arm64 intelchain binary
        run: |
          gpg --detach-sign intelchain-arm64
          sha256sum intelchain-arm64 >> intelchain-arm64.sha256

      - name: Signed amd64 intelchain binary
        run: |
          shasum -a 256 intelchain-macos.zip >> intelchain-macos.zip.sha256

      - name: Get tag message
        env:
          TAG_SHA: ${{ github.event.after }}
        run: |
          touch ./tag_message.md
          TAG_MESSAGE=$(git cat-file tag v$build_version | tail -n+6)
          echo -e "$TAG_MESSAGE\n\nThe released version: $build_version_long" >> ./tag_message.md
        working-directory: intelchain

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Mainnet Release ${{ env.build_version }}
          draft: true
          prerelease: false
          body_path: ./intelchain/tag_message.md

      - name: Upload intelchain binary for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-amd64
          asset_name: intelchain
          asset_content_type: application/octet-stream

      - name: Upload intelchain deb package for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-${{ env.build_version }}-${{ env.build_release }}.deb
          asset_name: intelchain-${{ env.build_version }}.deb
          asset_content_type: application/x-deb

      - name: Upload intelchain rpm package for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-${{ env.build_version }}-${{ env.build_release }}.x86_64.rpm
          asset_name: intelchain-${{ env.build_version }}.x86_64.rpm
          asset_content_type: application/x-rpm

      - name: Upload intelchain amd64 binary for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-amd64
          asset_name: intelchain-amd64
          asset_content_type: application/octet-stream

      - name: Upload sha256 signature of intelchain amd64 binary for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-amd64.sha256
          asset_name: intelchain-amd64.sha256
          asset_content_type: text/plain

      - name: Upload gpg signature of intelchain amd64 binary for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-amd64.sig
          asset_name: intelchain-amd64.sig
          asset_content_type: application/octet-stream

      - name: Upload intelchain arm64 binary for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-arm64
          asset_name: intelchain-arm64
          asset_content_type: application/octet-stream

      - name: Upload sha256 signature of intelchain arm64 binary for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-arm64.sha256
          asset_name: intelchain-arm64.sha256
          asset_content_type: text/plain

      - name: Upload gpg signature of intelchain arm64 binary for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-arm64.sig
          asset_name: intelchain-arm64.sig
          asset_content_type: application/octet-stream

      - name: Upload intelchain binary for MacOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-macos.zip
          asset_name: intelchain-macos-${{ env.build_version }}.zip
          asset_content_type: application/zip

      - name: Upload sha256 signature of intelchain for MacOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./intelchain-macos.zip.sha256
          asset_name: intelchain-macos.zip.sha256
          asset_content_type: text/plain
